changelog:
  exclude:
    authors:
      - github-actions[bot]
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
    - title: Features
      labels:
        - feat
        - feature
        - enhancement
    - title: Fixes
      labels:
        - fix
        - bug
    - title: Performance
      labels:
        - perf
        - performance
    - title: Documentation
      labels:
        - docs
        - documentation
    - title: Maintenance
      labels:
        - chore
        - ci
        - dependencies
        - refactor
        - test
    - title: Other Changes
      labels:
        - "*"
